// Solfeggio Frequencies - Ancient musical scale with traditional spiritual significance
// Note: Presented for relaxation, meditation, and acoustic reflection
export const SOLFEGGIO_FREQUENCIES = [
  {
    name: "Foundation Pure",
    hz: 174,
    description: "Traditional foundation frequency for grounding and deep relaxation",
    color: "#8B5CF6",
    gradient: ["#8B5CF6", "#6366F1"] as const,
    benefits: ["Deep grounding and stability", "Physical comfort", "Foundation tone", "Sense of security"],
  },
  {
    name: "Transformation Pure",
    hz: 285,
    description: "Traditional transformation frequency for acoustic renewal and balance",
    color: "#10B981",
    gradient: ["#10B981", "#059669"] as const,
    benefits: ["Restorative atmosphere", "Harmonic balance", "Energy restoration", "Sense of renewal"],
  },
  {
    name: "Liberation Pure",
    hz: 396,
    description: "Traditional liberation frequency for releasing stress and worry",
    color: "#F59E0B",
    gradient: ["#F59E0B", "#D97706"] as const,
    benefits: ["Stress release", "Emotional ease", "Mindful liberation", "Root chakra harmony"],
  },
  {
    name: "Change Pure",
    hz: 417,
    description: "Traditional change frequency for facilitating transformation and focus",
    color: "#EF4444",
    gradient: ["#EF4444", "#DC2626"] as const,
    benefits: ["Facilitating change", "Clearing mental clutter", "Transformative energy", "Sacral chakra balance"],
  },
  {
    name: "Love & Miracles Pure",
    hz: 528,
    description: "Traditional love frequency for harmony, peace, and heart-centered meditation",
    color: "#EC4899",
    gradient: ["#EC4899", "#DB2777"] as const,
    benefits: ["Heart-centered peace", "Love frequency harmony", "Calming reflection", "Heart chakra balance"],
  },
  {
    name: "Relationships Pure",
    hz: 639,
    description: "Traditional relationship frequency for connection and open communication",
    color: "#06B6D4",
    gradient: ["#06B6D4", "#0891B2"] as const,
    benefits: ["Harmonious connection", "Enhanced empathy", "Social openness", "Emotional balance"],
  },
  {
    name: "Intuition Pure",
    hz: 741,
    description: "Traditional intuition frequency for awakening inner wisdom and clarity",
    color: "#8B5CF6",
    gradient: ["#8B5CF6", "#7C3AED"] as const,
    benefits: ["Awakening intuition", "Mental clarity", "Creative expression", "Throat chakra balance"],
  },
  {
    name: "Spiritual Order Pure",
    hz: 852,
    description: "Traditional spiritual frequency for returning to inner stillness",
    color: "#A855F7",
    gradient: ["#A855F7", "#9333EA"] as const,
    benefits: ["Inner stillness", "Divine balance", "Third eye focus", "Meditative awareness"],
  },
  {
    name: "Divine Connection Pure",
    hz: 963,
    description: "Traditional crown frequency for higher consciousness and clarity",
    color: "#C084FC",
    gradient: ["#C084FC", "#A855F7"] as const,
    benefits: ["Crown chakra connection", "Expanded awareness", "Deep meditation", "Universal unity"],
  },
];

// Chakra Frequencies - Based on traditional sound healing associations
export const CHAKRA_FREQUENCIES = [
  {
    name: "Root Chakra Pure",
    hz: 194.18,
    description: "Traditional root chakra frequency for grounding and physical presence",
    color: "#DC2626",
    gradient: ["#DC2626", "#991B1B"] as const,
    element: "Earth",
    benefits: ["Deep grounding", "Physical presence", "Stability", "Earth connection"],
  },
  {
    name: "Sacral Chakra Pure",
    hz: 210.42,
    description: "Traditional sacral chakra frequency for creative flow and passion",
    color: "#EA580C",
    gradient: ["#EA580C", "#C2410C"] as const,
    element: "Water",
    benefits: ["Creative energy flow", "Emotional fluidity", "Sensory awareness", "Passion activation"],
  },
  {
    name: "Solar Plexus Pure",
    hz: 126.22,
    description: "Traditional solar plexus frequency for confidence and motivation",
    color: "#F59E0B",
    gradient: ["#F59E0B", "#D97706"] as const,
    element: "Fire",
    benefits: ["Personal empowerment", "Confidence building", "Willpower activation", "Self-esteem support"],
  },
  {
    name: "Heart Chakra Pure",
    hz: 341.3,
    description: "Traditional heart chakra frequency for compassion and emotional warmth",
    color: "#10B981",
    gradient: ["#10B981", "#059669"] as const,
    element: "Air",
    benefits: ["Compassion expansion", "Emotional warmth", "Heart opening", "Inner harmony"],
  },
  {
    name: "Throat Chakra Pure",
    hz: 384,
    description: "Traditional throat chakra frequency for authentic expression",
    color: "#06B6D4",
    gradient: ["#06B6D4", "#0891B2"] as const,
    element: "Space",
    benefits: ["Clear expression", "Authentic voice", "Communication ease", "Creative resonance"],
  },
  {
    name: "Third Eye Pure",
    hz: 426.7,
    description: "Traditional third eye frequency for intuition and insight",
    color: "#6366F1",
    gradient: ["#6366F1", "#4F46E5"] as const,
    element: "Light",
    benefits: ["Enhanced intuition", "Inner vision", "Meditative insight", "Mental focus"],
  },
  {
    name: "Crown Chakra Pure",
    hz: 963,
    description: "Traditional crown chakra frequency for spiritual connection",
    color: "#8B5CF6",
    gradient: ["#8B5CF6", "#7C3AED"] as const,
    element: "Thought",
    benefits: ["Spiritual awareness", "Meditative unity", "Transcendent stillness", "Universal harmony"],
  },
];

// Brainwave Entrainment Frequencies
export const BINAURAL_BEATS = [
  {
    name: "Deep Delta Sleep",
    hz: 1.5,
    description: "Delta binaural frequency for deep, restorative sleep",
    color: "#0F172A",
    gradient: ["#0F172A", "#020617"] as const,
    range: "0.5-2 Hz",
    baseFreq: 200,
    beatFreq: 1.5,
    benefits: ["Restorative sleep", "Physical relaxation", "Nighttime calmness", "Deep rest"],
  },
  {
    name: "Delta Waves Pure",
    hz: 2.5,
    description: "Traditional delta beat for nighttime relaxation",
    color: "#1E293B",
    gradient: ["#1E293B", "#0F172A"] as const,
    range: "2-4 Hz",
    baseFreq: 200,
    beatFreq: 2.5,
    benefits: ["Deep sleep onset", "Restorative stillness", "Cellular rest", "Eased tension"],
  },
  {
    name: "Theta Deep Meditation",
    hz: 4.5,
    description: "Deep theta frequency for profound meditation and visualization",
    color: "#1F2937",
    gradient: ["#1F2937", "#111827"] as const,
    range: "4-5 Hz",
    baseFreq: 200,
    beatFreq: 4.5,
    benefits: ["Profound meditation", "Dream exploration", "Subconscious focus", "Creative flow"],
  },
  {
    name: "Theta Waves Pure",
    hz: 6,
    description: "Traditional theta frequency for creative reflection",
    color: "#374151",
    gradient: ["#374151", "#1F2937"] as const,
    range: "5-8 Hz",
    baseFreq: 200,
    beatFreq: 6,
    benefits: ["Enhanced creativity", "Intuitive insights", "Emotional stillness", "Mindful relaxation"],
  },
  {
    name: "Alpha Relaxation",
    hz: 8.5,
    description: "Lower alpha frequency for stress reduction and calm",
    color: "#047857",
    gradient: ["#047857", "#065F46"] as const,
    range: "8-9 Hz",
    baseFreq: 200,
    beatFreq: 8.5,
    benefits: ["Calm awareness", "Stress reduction", "Eased anxiety", "Mental tranquility"],
  },
  {
    name: "Alpha Waves Pure",
    hz: 10,
    description: "Traditional alpha frequency for relaxed alertness",
    color: "#059669",
    gradient: ["#059669", "#047857"] as const,
    range: "9-11 Hz",
    baseFreq: 200,
    beatFreq: 10,
    benefits: ["Relaxed focus", "Mental clarity", "Light meditation", "Mindful presence"],
  },
  {
    name: "Alpha Focus",
    hz: 12,
    description: "Upper alpha frequency for focused study and learning",
    color: "#10B981",
    gradient: ["#10B981", "#059669"] as const,
    range: "11-13 Hz",
    baseFreq: 200,
    beatFreq: 12,
    benefits: ["Focused study", "Memory retention", "Creative flow", "Calm concentration"],
  },
  {
    name: "SMR (Sensorimotor Rhythm)",
    hz: 14,
    description: "Sensorimotor rhythm for steady attention and poise",
    color: "#F59E0B",
    gradient: ["#F59E0B", "#D97706"] as const,
    range: "12-15 Hz",
    baseFreq: 200,
    beatFreq: 14,
    benefits: ["Steady attention", "Calm focus", "Body awareness", "Relaxed alertness"],
  },
  {
    name: "Beta Focus",
    hz: 16,
    description: "Lower beta frequency for active mental engagement",
    color: "#EF4444",
    gradient: ["#EF4444", "#DC2626"] as const,
    range: "15-18 Hz",
    baseFreq: 200,
    beatFreq: 16,
    benefits: ["Active concentration", "Mental clarity", "Problem solving", "Alertness"],
  },
  {
    name: "Beta Waves Pure",
    hz: 20,
    description: "Traditional beta frequency for analytical thinking",
    color: "#DC2626",
    gradient: ["#DC2626", "#B91C1C"] as const,
    range: "18-25 Hz",
    baseFreq: 200,
    beatFreq: 20,
    benefits: ["Alert thinking", "Analytical focus", "Cognitive drive", "Task engagement"],
  },
  {
    name: "High Beta Energy",
    hz: 25,
    description: "High beta frequency for peak mental engagement",
    color: "#B91C1C",
    gradient: ["#B91C1C", "#991B1B"] as const,
    range: "25-30 Hz",
    baseFreq: 200,
    beatFreq: 25,
    benefits: ["Peak engagement", "Energetic focus", "Complex processing", "Mental drive"],
  },
  {
    name: "Gamma Waves Pure",
    hz: 40,
    description: "Traditional gamma frequency for heightened perception",
    color: "#7C3AED",
    gradient: ["#7C3AED", "#6D28D9"] as const,
    range: "30-50 Hz",
    baseFreq: 200,
    beatFreq: 40,
    benefits: ["Heightened perception", "Cognitive clarity", "Binding awareness", "Focused mindfulness"],
  },
  {
    name: "High Gamma Insight",
    hz: 60,
    description: "High gamma frequency for meditative insight",
    color: "#6D28D9",
    gradient: ["#6D28D9", "#5B21B6"] as const,
    range: "50-80 Hz",
    baseFreq: 200,
    beatFreq: 60,
    benefits: ["Peak insight", "Epiphany meditation", "Advanced mindfulness", "Transcendent stillness"],
  },
];

export const HEALING_FREQUENCIES = [
  {
    name: "Schumann Resonance",
    hz: 7.83,
    description: "Earth's natural resonance frequency for grounding and balance",
    gradient: ["#10B981", "#059669"] as const,
    benefits: ["Natural Grounding", "Stress Reduction", "Circadian Balance"],
    duration: "20-30 minutes",
    research: "Documented natural Earth resonance frequency",
  },
  {
    name: "Pain Relief (Solfeggio)",
    hz: 174,
    description: "Traditional foundation frequency for physical relaxation",
    gradient: ["#8B5CF6", "#6366F1"] as const,
    benefits: ["Deep Comfort", "Muscle Relaxation", "Grounding"],
    duration: "15-25 minutes",
    research: "Traditional Solfeggio sound therapy tone",
  },
  {
    name: "Love Frequency",
    hz: 528,
    description: "Traditional love and harmony frequency",
    gradient: ["#EC4899", "#DB2777"] as const,
    benefits: ["Stress Reduction", "Positive Reflection", "Inner Harmony"],
    duration: "20-30 minutes",
    research: "Studied for positive mood and stress reduction",
  },
  {
    name: "40 Hz Gamma",
    hz: 40,
    description: "Cognitive focus and mental synchrony",
    gradient: ["#7C3AED", "#6D28D9"] as const,
    benefits: ["Cognitive Focus", "Memory Support", "Mental Clarity"],
    duration: "15-20 minutes",
    research: "Studied for cognitive synchrony and focus",
  },
  {
    name: "110 Hz Bone Resonance",
    hz: 110,
    description: "Acoustic resonance frequency inspired by ancient architecture",
    gradient: ["#F59E0B", "#D97706"] as const,
    benefits: ["Acoustic Resonance", "Deep Relaxation", "Physical Grounding"],
    duration: "20-30 minutes",
    research: "Documented in ancient stone chambers and acoustic studies",
  },
];

export const SLEEP_FREQUENCIES = [
  {
    name: "Deep Sleep (Delta)",
    hz: 1.5,
    description: "Delta waves for restorative sleep environment",
    gradient: ["#1E293B", "#0F172A"] as const,
    duration: "60-90 minutes",
    stage: "Deep NREM Rest",
    research: "Targeted brainwave entrainment for sleep",
  },
  {
    name: "REM Sleep (Theta)",
    hz: 4.5,
    description: "Theta waves for restful dream state",
    gradient: ["#374151", "#1F2937"] as const,
    duration: "45-60 minutes",
    stage: "Dream State",
    research: "Associated with theta wave dream patterns",
  },
  {
    name: "Sleep Transition",
    hz: 8,
    description: "Alpha waves for relaxing sleep onset",
    gradient: ["#4B5563", "#374151"] as const,
    duration: "20-30 minutes",
    stage: "Sleep Onset",
    research: "Helps transition from active mind to sleep",
  },
  {
    name: "Light Sleep (Theta)",
    hz: 6,
    description: "Theta waves for gentle, light relaxation",
    gradient: ["#6366F1", "#4F46E5"] as const,
    duration: "30-45 minutes",
    stage: "Light NREM Rest",
    research: "Associated with light meditative sleep",
  },
];

export const WEALTH_FREQUENCIES = [
  {
    name: "Abundance Frequency",
    hz: 888,
    description: "Traditional numerological frequency for prosperity focus",
    gradient: ["#F59E0B", "#D97706"] as const,
    affirmations: [
      "I am aligned with abundance",
      "Opportunities flow to me easily",
      "I create value with confidence",
      "My mind is open to growth",
    ],
    note: "Based on traditional numerological symbolism",
  },
  {
    name: "Natural Harmony",
    hz: 432,
    description: "Natural tuning for harmonious mindset",
    gradient: ["#10B981", "#059669"] as const,
    affirmations: [
      "I achieve my goals with calm focus",
      "Harmony is my natural state",
      "I bring clarity to my work",
      "Opportunities unfold naturally",
    ],
    note: "Natural 432 Hz tuning",
  },
  {
    name: "Manifestation Power",
    hz: 528,
    description: "Love frequency for focused intention and goals",
    gradient: ["#EC4899", "#DB2777"] as const,
    affirmations: [
      "I focus my mind on positive outcomes",
      "My actions align with my vision",
      "I cultivate gratitude daily",
      "My clarity drives my success",
    ],
    note: "Traditional Solfeggio frequency for positive change",
  },
  {
    name: "Alpha Success State",
    hz: 10,
    description: "Relaxed focus for mental clarity and goal setting",
    gradient: ["#8B5CF6", "#7C3AED"] as const,
    affirmations: [
      "I make clear, grounded decisions",
      "Focus and calm guide my progress",
      "I am capable and resilient",
      "My mind is clear and purposeful",
    ],
    note: "Alpha wave entrainment for focused mindset",
  },
];

export const SCIENTIFIC_FREQUENCIES = [
  {
    name: "Schumann Resonance",
    hz: 7.83,
    description: "Earth's natural resonance frequency for grounding",
    category: "Natural",
    research: "Documented atmospheric electromagnetic phenomenon",
    benefits: ["Natural Grounding", "Stress Reduction", "Circadian Support", "Calm Presence"],
  },
  {
    name: "40 Hz Gamma Pure",
    hz: 40,
    description: "Gamma frequency for cognitive clarity and focus",
    category: "Cognitive",
    research: "Studied for neural synchrony and attention",
    benefits: ["Cognitive Clarity", "Sharpened Focus", "Neural Synchrony", "Active Awareness"],
  },
  {
    name: "110 Hz Resonance Pure",
    hz: 110,
    description: "Acoustic resonance frequency inspired by ancient temples",
    category: "Archaeological",
    research: "Studied in ancient stone acoustics",
    benefits: ["Deep Meditation", "Resonant Stillness", "Calming Atmosphere", "Physical Presence"],
  },
  {
    name: "432 Hz Natural Tuning",
    hz: 432,
    description: "Traditional natural harmonic tuning",
    category: "Musical",
    research: "Acoustic alternative to standard concert pitch",
    benefits: ["Natural Harmony", "Stress Reduction", "Acoustic Ease", "Musical Balance"],
  },
];
