// Solfeggio Frequencies - Ancient musical scale with traditional spiritual significance
// Note: Presented for relaxation, meditation, and acoustic reflection
export const SOLFEGGIO_FREQUENCIES = [
  {
    name: "Foundation Pure",
    hz: 174,
    description: "A low-frequency pure tone presented for grounding, quiet reflection and relaxation",
    color: "#8B5CF6",
    gradient: ["#8B5CF6", "#6366F1"] as const,
    benefits: ["Grounding and stability", "Physical comfort and ease", "Contemplative atmosphere", "Mindful relaxation"],
  },
  {
    name: "Transformation Pure",
    hz: 285,
    description: "A pure tone associated in contemporary sound-healing traditions with renewal, restoration and transition",
    color: "#10B981",
    gradient: ["#10B981", "#059669"] as const,
    benefits: ["Restorative atmosphere", "Harmonic balance", "Contemplative renewal", "Sense of tranquility"],
  },
  {
    name: "Liberation Pure",
    hz: 396,
    description: "A pure tone traditionally associated with release, grounding and letting go of worry",
    color: "#F59E0B",
    gradient: ["#F59E0B", "#D97706"] as const,
    benefits: ["Stress release", "Emotional ease", "Mindful liberation", "Root chakra harmony"],
  },
  {
    name: "Change Pure",
    hz: 417,
    description: "A pure tone associated with change, transition and fresh perspective",
    color: "#EF4444",
    gradient: ["#EF4444", "#DC2626"] as const,
    benefits: ["Facilitating perspective", "Clearing mental clutter", "Transformative reflection", "Sacral chakra balance"],
  },
  {
    name: "Love & Miracles Pure",
    hz: 528,
    description: "A 528-Hz pure tone associated with love, harmony and transformation in contemporary wellness traditions",
    color: "#EC4899",
    gradient: ["#EC4899", "#DB2777"] as const,
    benefits: ["Heart-centered peace", "Love frequency harmony", "Calming reflection", "Heart chakra balance"],
  },
  {
    name: "Relationships Pure",
    hz: 639,
    description: "A pure tone associated in contemporary Solfeggio traditions with connection, compassion and communication",
    color: "#06B6D4",
    gradient: ["#06B6D4", "#0891B2"] as const,
    benefits: ["Harmonious connection", "Enhanced empathy", "Social openness", "Emotional balance"],
  },
  {
    name: "Intuition Pure",
    hz: 741,
    description: "A pure tone traditionally associated with clarity, intuition and creative reflection",
    color: "#8B5CF6",
    gradient: ["#8B5CF6", "#7C3AED"] as const,
    benefits: ["Awakening intuition", "Mental clarity", "Creative expression", "Throat chakra balance"],
  },
  {
    name: "Spiritual Order Pure",
    hz: 852,
    description: "A pure tone associated with inner stillness and spiritual contemplation",
    color: "#A855F7",
    gradient: ["#A855F7", "#9333EA"] as const,
    benefits: ["Inner stillness", "Quiet balance", "Third eye focus", "Meditative awareness"],
  },
  {
    name: "Divine Connection Pure",
    hz: 963,
    description: "A pure tone associated with crown awareness, contemplation and spiritual connection in contemporary traditions",
    color: "#C084FC",
    gradient: ["#C084FC", "#A855F7"] as const,
    benefits: ["Crown chakra connection", "Expanded awareness", "Deep meditation", "Universal harmony"],
  },
];

// Chakra Frequencies - Based on contemporary sound healing frameworks
export const CHAKRA_FREQUENCIES = [
  {
    name: "Root Chakra Pure",
    hz: 194.18,
    description: "A contemporary meditation framework tone for grounding, physical presence and reflective stability",
    color: "#DC2626",
    gradient: ["#DC2626", "#991B1B"] as const,
    element: "Earth",
    benefits: ["Deep grounding", "Physical presence", "Reflective stability", "Earth symbolism connection"],
  },
  {
    name: "Sacral Chakra Pure",
    hz: 210.42,
    description: "A contemporary meditation framework tone for creativity, emotional reflection and flow",
    color: "#EA580C",
    gradient: ["#EA580C", "#C2410C"] as const,
    element: "Water",
    benefits: ["Creative reflection", "Emotional fluidity", "Sensory awareness", "Water symbolism connection"],
  },
  {
    name: "Solar Plexus Pure",
    hz: 126.22,
    description: "A contemporary meditation framework tone for confidence, agency and focused reflection",
    color: "#F59E0B",
    gradient: ["#F59E0B", "#D97706"] as const,
    element: "Fire",
    benefits: ["Personal empowerment", "Confidence building", "Willpower reflection", "Fire symbolism connection"],
  },
  {
    name: "Heart Chakra Pure",
    hz: 341.3,
    description: "A contemporary meditation framework tone for compassion, warmth and heart-centered meditation",
    color: "#10B981",
    gradient: ["#10B981", "#059669"] as const,
    element: "Air",
    benefits: ["Compassion expansion", "Emotional warmth", "Heart-centered peace", "Air symbolism connection"],
  },
  {
    name: "Throat Chakra Pure",
    hz: 384,
    description: "A contemporary meditation framework tone for communication and vocal expression",
    color: "#06B6D4",
    gradient: ["#06B6D4", "#0891B2"] as const,
    element: "Space",
    benefits: ["Clear expression", "Authentic voice", "Communication ease", "Space symbolism connection"],
  },
  {
    name: "Third Eye Pure",
    hz: 426.7,
    description: "A contemporary meditation framework tone for intuition, imagination and reflective attention",
    color: "#6366F1",
    gradient: ["#6366F1", "#4F46E5"] as const,
    element: "Light",
    benefits: ["Intuitive reflection", "Inner vision", "Meditative insight", "Light symbolism connection"],
  },
  {
    name: "Crown Chakra Pure",
    hz: 963,
    description: "A contemporary meditation framework tone for contemplation, stillness and spiritual reflection",
    color: "#8B5CF6",
    gradient: ["#8B5CF6", "#7C3AED"] as const,
    element: "Thought",
    benefits: ["Spiritual awareness", "Meditative unity", "Transcendent stillness", "Thought symbolism connection"],
  },
];

// Brainwave Entrainment Frequencies
export const BINAURAL_BEATS = [
  {
    name: "Deep Rest Delta",
    hz: 1.5,
    description: "Low-beat listening experience for quiet wind-down and pre-sleep rest",
    color: "#0F172A",
    gradient: ["#0F172A", "#020617"] as const,
    range: "0.5-2 Hz",
    baseFreq: 200,
    beatFreq: 1.5,
    benefits: ["Restful wind-down", "Physical relaxation", "Nighttime calmness", "Pre-sleep quiet"],
  },
  {
    name: "Delta Waves Pure",
    hz: 2.5,
    description: "Delta-range relaxation tone for evening rest and relaxation",
    color: "#1E293B",
    gradient: ["#1E293B", "#0F172A"] as const,
    range: "2-4 Hz",
    baseFreq: 200,
    beatFreq: 2.5,
    benefits: ["Evening relaxation", "Restorative stillness", "Eased tension", "Quiet reflection"],
  },
  {
    name: "Theta Deep Meditation",
    hz: 4.5,
    description: "Theta-range listening experience for deep meditation and creative reflection",
    color: "#1F2937",
    gradient: ["#1F2937", "#111827"] as const,
    range: "4-5 Hz",
    baseFreq: 200,
    beatFreq: 4.5,
    benefits: ["Profound meditation", "Reflective imagery", "Subconscious focus", "Creative reflection"],
  },
  {
    name: "Theta Waves Pure",
    hz: 6,
    description: "Theta-range relaxed reflection tone for creative sessions",
    color: "#374151",
    gradient: ["#374151", "#1F2937"] as const,
    range: "5-8 Hz",
    baseFreq: 200,
    beatFreq: 6,
    benefits: ["Relaxed reflection", "Intuitive insights", "Emotional stillness", "Mindful relaxation"],
  },
  {
    name: "Alpha Relaxation",
    hz: 8.5,
    description: "Alpha-range calm attention tone for stress reduction and tranquility",
    color: "#047857",
    gradient: ["#047857", "#065F46"] as const,
    range: "8-9 Hz",
    baseFreq: 200,
    beatFreq: 8.5,
    benefits: ["Calm awareness", "Stress reduction", "Eased tension", "Mental tranquility"],
  },
  {
    name: "Alpha Waves Pure",
    hz: 10,
    description: "Alpha-range relaxation tone for light meditation and presence",
    color: "#059669",
    gradient: ["#059669", "#047857"] as const,
    range: "9-11 Hz",
    baseFreq: 200,
    beatFreq: 10,
    benefits: ["Relaxed focus", "Mental clarity", "Light meditation", "Mindful presence"],
  },
  {
    name: "Alpha Focus",
    hz: 12,
    description: "Alpha-range calm concentration tone for study and reading",
    color: "#10B981",
    gradient: ["#10B981", "#059669"] as const,
    range: "11-13 Hz",
    baseFreq: 200,
    beatFreq: 12,
    benefits: ["Focused study", "Attentive listening", "Creative flow", "Calm concentration"],
  },
  {
    name: "SMR (Sensorimotor Rhythm)",
    hz: 14,
    description: "SMR-range steady attention tone for physical poise and focus",
    color: "#F59E0B",
    gradient: ["#F59E0B", "#D97706"] as const,
    range: "12-15 Hz",
    baseFreq: 200,
    beatFreq: 14,
    benefits: ["Steady attention", "Calm focus", "Body awareness", "Relaxed alertness"],
  },
  {
    name: "Beta Focus",
    hz: 16,
    description: "Beta-range alert structured attention tone for active tasks",
    color: "#EF4444",
    gradient: ["#EF4444", "#DC2626"] as const,
    range: "15-18 Hz",
    baseFreq: 200,
    beatFreq: 16,
    benefits: ["Active concentration", "Mental clarity", "Structured focus", "Alertness"],
  },
  {
    name: "Beta Waves Pure",
    hz: 20,
    description: "Higher-beta focused activity tone for analytical engagement",
    color: "#DC2626",
    gradient: ["#DC2626", "#B91C1C"] as const,
    range: "18-25 Hz",
    baseFreq: 200,
    beatFreq: 20,
    benefits: ["Alert thinking", "Analytical focus", "Task engagement", "Active mind"],
  },
  {
    name: "High Beta Energy",
    hz: 25,
    description: "Short higher-beta active-focus tone for intense mental activity",
    color: "#B91C1C",
    gradient: ["#B91C1C", "#991B1B"] as const,
    range: "25-30 Hz",
    baseFreq: 200,
    beatFreq: 25,
    benefits: ["Active focus", "Energetic drive", "Complex processing", "Short-term engagement"],
  },
  {
    name: "Gamma Waves Pure",
    hz: 40,
    description: "40-Hz gamma research-inspired listening experience for attentive focus",
    color: "#7C3AED",
    gradient: ["#7C3AED", "#6D28D9"] as const,
    range: "30-50 Hz",
    baseFreq: 200,
    beatFreq: 40,
    benefits: ["Cognitive clarity backdrop", "Attentive awareness", "Focused mindfulness", "Research-inspired focus"],
  },
  {
    name: "High Gamma Insight",
    hz: 60,
    description: "Advanced attentive/meditative listening tone for quiet contemplation",
    color: "#6D28D9",
    gradient: ["#6D28D9", "#5B21B6"] as const,
    range: "50-80 Hz",
    baseFreq: 200,
    beatFreq: 60,
    benefits: ["Attentive insight", "Advanced mindfulness", "Quiet contemplation", "Reflective stillness"],
  },
];

export const HEALING_FREQUENCIES = [
  {
    name: "Schumann Resonance",
    hz: 7.83,
    description: "Earth has naturally occurring electromagnetic Schumann resonances. This app provides a Schumann-inspired listening experience; it does not reproduce Earth's electromagnetic field.",
    gradient: ["#10B981", "#059669"] as const,
    benefits: ["Natural Grounding Atmosphere", "Stress Reduction", "Circadian Support"],
    duration: "5-20 minutes",
    research: "Documented atmospheric electromagnetic phenomenon near 7.83 Hz; phone audio provides an acoustic listening experience.",
  },
  {
    name: "Physical Ease",
    hz: 174,
    description: "Low-frequency relaxation tone inspired by contemporary sound-healing practice. Not a pain treatment.",
    gradient: ["#8B5CF6", "#6366F1"] as const,
    benefits: ["Deep Comfort", "Relaxation", "Grounding"],
    duration: "5-20 minutes",
    research: "Traditional Solfeggio sound therapy foundation tone.",
  },
  {
    name: "Love Frequency",
    hz: 528,
    description: "528-Hz listening experience associated with love, harmony and transformation in contemporary wellness traditions.",
    gradient: ["#EC4899", "#DB2777"] as const,
    benefits: ["Stress Reduction", "Positive Reflection", "Inner Harmony"],
    duration: "5-20 minutes",
    research: "Preliminary study noted mood and autonomic changes after 528-Hz-tuned music.",
  },
  {
    name: "40 Hz Gamma",
    hz: 40,
    description: "Research-inspired 40-Hz listening experience connected to gamma-range neuroscience research.",
    gradient: ["#7C3AED", "#6D28D9"] as const,
    benefits: ["Cognitive Clarity Backdrop", "Attentive Focus", "Research-Inspired Listening"],
    duration: "5-20 minutes",
    research: "40-Hz sensory stimulation is an active area of cognitive neuroscience research.",
  },
  {
    name: "110 Hz Resonance",
    hz: 110,
    description: "Experimental/archaeoacoustic-inspired tone for reflective listening. No established bone-repair effect.",
    gradient: ["#F59E0B", "#D97706"] as const,
    benefits: ["Acoustic Resonance", "Deep Relaxation", "Reflective Grounding"],
    duration: "5-20 minutes",
    research: "Documented in acoustic studies of ancient stone structures.",
  },
];

export const SLEEP_FREQUENCIES = [
  {
    name: "Deep Rest Delta",
    hz: 1.5,
    description: "Low-beat listening experience for quiet wind-down and rest",
    gradient: ["#1E293B", "#0F172A"] as const,
    duration: "5-20 minutes",
    stage: "Evening Rest Routine",
    research: "Targeted binaural audio for relaxation and wind-down.",
  },
  {
    name: "Rest & Dreaming Theta",
    hz: 4.5,
    description: "Theta-range listening experience for relaxation and pre-sleep reflection",
    gradient: ["#374151", "#1F2937"] as const,
    duration: "5-20 minutes",
    stage: "Pre-Sleep Reflection",
    research: "Associated with theta brainwave relaxation states.",
  },
  {
    name: "Sleep Transition",
    hz: 8,
    description: "8-Hz listening experience for a quieter, more relaxed pre-sleep routine",
    gradient: ["#4B5563", "#374151"] as const,
    duration: "5-20 minutes",
    stage: "Wind-Down Onset",
    research: "Helps transition from active daytime thinking to evening quiet.",
  },
  {
    name: "Evening Theta",
    hz: 6,
    description: "Theta-range listening experience for relaxation and pre-sleep reflection",
    gradient: ["#6366F1", "#4F46E5"] as const,
    duration: "5-20 minutes",
    stage: "Quiet Wind-Down",
    research: "Associated with meditative relaxation prior to sleep.",
  },
];

export const WEALTH_FREQUENCIES = [
  {
    name: "Abundance Frequency",
    hz: 888,
    description: "Numerological listening experience centred on abundance-focused reflection",
    gradient: ["#F59E0B", "#D97706"] as const,
    affirmations: [
      "I align my focus with constructive growth",
      "Opportunities arise through clear action",
      "I create value with confidence and clarity",
      "My mind is open to learning and progress",
    ],
    note: "Based on traditional numerological symbolism for goal reflection",
  },
  {
    name: "Natural Harmony",
    hz: 432,
    description: "432-Hz alternative tuning experience; evidence remains preliminary",
    gradient: ["#10B981", "#059669"] as const,
    affirmations: [
      "I achieve my goals with calm focus",
      "Harmony is a helpful state of mind",
      "I bring clarity to my work",
      "Progress unfolds with steady effort",
    ],
    note: "Alternative 432 Hz tuning reference",
  },
  {
    name: "Manifestation Power",
    hz: 528,
    description: "528-Hz listening paired with affirmations or personal goal reflection; no claim of supernatural causation",
    gradient: ["#EC4899", "#DB2777"] as const,
    affirmations: [
      "I focus my mind on positive outcomes",
      "My actions align with my vision",
      "I cultivate gratitude daily",
      "My clarity drives my progress",
    ],
    note: "Traditional Solfeggio frequency for positive intention reflection",
  },
  {
    name: "Alpha Success State",
    hz: 10,
    description: "Alpha-range listening experience for calm goal reflection and focused intention",
    gradient: ["#8B5CF6", "#7C3AED"] as const,
    affirmations: [
      "I make clear, grounded decisions",
      "Focus and calm guide my work",
      "I am capable and resilient",
      "My mind is clear and purposeful",
    ],
    note: "Alpha wave listening experience for focused mindset",
  },
];

export const SCIENTIFIC_FREQUENCIES = [
  {
    name: "Schumann Resonance",
    hz: 7.83,
    description: "Science-oriented explanation entry distinguishing atmospheric electromagnetic resonance from phone audio",
    category: "Natural",
    research: "Documented atmospheric electromagnetic phenomenon near 7.83 Hz; phone audio provides an acoustic listening experience.",
    benefits: ["Natural Grounding Atmosphere", "Stress Reduction", "Circadian Support", "Calm Presence"],
  },
  {
    name: "40 Hz Gamma Pure",
    hz: 40,
    description: "Research-inspired 40-Hz tone associated with gamma-range neuroscience research",
    category: "Cognitive",
    research: "Studied in neuroscience for neural synchrony and attention.",
    benefits: ["Cognitive Clarity Backdrop", "Attentive Focus", "Research-Inspired Listening", "Active Awareness"],
  },
  {
    name: "110 Hz Resonance Pure",
    hz: 110,
    description: "Experimental/archaeoacoustic-inspired tone; no established therapeutic effect",
    category: "Archaeological",
    research: "Studied in acoustic research of ancient stone chambers.",
    benefits: ["Acoustic Resonance", "Resonant Stillness", "Calming Atmosphere", "Reflective Presence"],
  },
  {
    name: "432 Hz Natural Tuning",
    hz: 432,
    description: "432-Hz tuning reference for exploring alternative musical tuning",
    category: "Musical",
    research: "Acoustic alternative to standard 440 Hz concert pitch; small pilot studies report preliminary physiological differences.",
    benefits: ["Alternative Tuning Experience", "Stress Reduction", "Acoustic Ease", "Musical Balance"],
  },
];
