import { CanonicalArticle, ArticleCategory, ContentStatus } from '../types/content';

const now = '2026-01-01T00:00:00.000Z';

export function getArticlesSeed(): CanonicalArticle[] {
  return [
    {
      id: 'article-1',
      title: 'Solfeggio Frequencies: Ancient Tones for Modern Healing',
      content: `Solfeggio frequencies represent a system of musical tones popular in contemporary sound-healing and wellness traditions. The modern scale commonly includes 396 Hz, 417 Hz, 528 Hz, 639 Hz, 741 Hz, and 852 Hz.\n\nWhile popular accounts frequently attribute these tones directly to ancient Medieval Gregorian chants or biblical numerology rediscovered in the 1970s by Dr. Joseph Puleo, historical claims linking the complete modern system to ancient practice should be treated cautiously.\n\nEach frequency carries strong contemporary wellness associations: 396 Hz with letting go of worry; 417 Hz with change; 528 Hz with harmony and love; 639 Hz with interpersonal connection; 741 Hz with clarity; and 852 Hz with inner stillness.\n\nFrom a scientific perspective, evidence remains exploratory. Listeners use these tones for relaxation, meditation, and personal reflection.`,
      category: ArticleCategory.SOLFEGGIO,
      tags: ['solfeggio', 'basics', 'wellness', 'tradition'],
      isPremium: false,
      status: ContentStatus.PUBLISHED,
      author: 'Frequency Lab',
      readTime: 6,
      difficulty: 'Beginner',
      keyPoints: [
        'The modern Solfeggio system commonly includes 396, 417, 528, 639, 741 and 852 Hz',
        'These frequencies have strong contemporary spiritual and wellness associations',
        'Historical claims linking the complete modern system directly to ancient Gregorian practice should be treated cautiously',
        '528 Hz has small exploratory human evidence but no established DNA-repair effect',
      ],
      practicalTips: [
        'Start with 5–20 minutes at a comfortable volume',
        'Choose a time and environment that fits your routine',
        'Notice subjective relaxation rather than expecting predetermined physiological outcomes',
        'Keep a quiet journal to track personal mindfulness shifts',
      ],
      iconIdentifier: 'Music',
      colorToken: '#F472B6',
      publishedAt: now,
      createdAt: now,
      updatedAt: now,
      provenance: 'system_seed',
      seedVersion: 1,
      createdBy: 'system_seed',
    },
    {
      id: 'article-2',
      title: 'Brainwave Entrainment: Science of the Synchronised Mind',
      content: `Binaural beats are a genuine psychoacoustic percept that occurs when two slightly different frequencies are presented separately to each ear through stereo headphones (for example, 200 Hz in the left ear and 210 Hz in the right ear, creating a perceived 10 Hz phantom beat).\n\nBrainwaves naturally shift across Delta (0.5–4 Hz), Theta (4–8 Hz), Alpha (8–13 Hz), Beta (13–30 Hz), and Gamma (30+ Hz) ranges during different states of arousal and sleep.\n\nScientific evidence regarding reliable brainwave entrainment (the Frequency Following Response) remains mixed. A 2023 systematic review of 14 studies found contradictory results regarding entrainment, while a 2019 meta-analysis noted potential heterogeneous benefits for anxiety and focus in some participants.\n\nBinaural beats offer a helpful backdrop for meditation and focus, but a specific beat should not be viewed as a guaranteed method to induce a precise neural state.`,
      category: ArticleCategory.BRAINWAVES,
      tags: ['brainwaves', 'focus', 'science', 'binaural'],
      isPremium: false,
      status: ContentStatus.PUBLISHED,
      author: 'Frequency Lab',
      readTime: 8,
      difficulty: 'Intermediate',
      keyPoints: [
        'Binaural beats occur when slightly different tones are presented separately to each ear',
        'Five primary brainwave ranges describe neural activity: Delta, Theta, Alpha, Beta, Gamma',
        'Stereo headphones are strictly required for binaural beat perception',
        'Scientific evidence for reliable brainwave entrainment remains mixed and study-dependent',
      ],
      practicalTips: [
        'Always use stereo headphones for binaural beat listening',
        'Choose a comfortable session length (5–20 minutes)',
        'Never drive, cycle or operate machinery while listening to binaural beats',
        'Avoid high-beta frequencies prior to sleeping',
      ],
      scientificBasis: 'Binaural beats are a psychoacoustic phenomenon. Meta-analyses (Garcia-Argibay et al., 2019) report possible effects on anxiety and focus, though systematic reviews (Ingendoh et al., 2023) highlight mixed entrainment evidence.',
      iconIdentifier: 'Brain',
      colorToken: '#818CF8',
      publishedAt: now,
      createdAt: now,
      updatedAt: now,
      provenance: 'system_seed',
      seedVersion: 1,
      createdBy: 'system_seed',
    },
    {
      id: 'article-3',
      title: 'Sleep & Sound: Building a Restful Listening Routine',
      content: `A quality night's rest is foundational to health and mental clarity. Sound and music offer a gentle, non-pharmaceutical approach to supporting a wind-down routine.\n\nA 2022 Cochrane systematic review concluded that music may help some adults improve subjective sleep quality. However, sleep cannot be reduced to a single frequency or tone.\n\nDelta (0.5–4 Hz) and Theta (4–8 Hz) describe brainwave ranges typical of deep NREM and REM sleep. Listening to low-beat audio during a pre-sleep routine can encourage relaxation, but does not guarantee the induction of specific sleep stages.\n\nTo build a healthy routine, listen at a comfortable, low volume during the 30–60 minutes before bed, in a dark, cool environment away from bright screens.`,
      category: ArticleCategory.SLEEP,
      tags: ['sleep', 'delta', 'theta', 'relaxation', 'wind-down'],
      isPremium: false,
      status: ContentStatus.PUBLISHED,
      author: 'Frequency Lab',
      readTime: 7,
      difficulty: 'Beginner',
      keyPoints: [
        'Music may help some people improve subjective sleep quality according to a 2022 Cochrane review',
        'Sleep cannot be reduced to one frequency or guaranteed sound trigger',
        'Delta and Theta describe neural activity ranges, not guaranteed externally induced sleep stages',
        'A calm environment and comfortable listening volume are essential',
      ],
      practicalTips: [
        'Begin your pre-sleep listening routine 30–45 minutes before bed',
        'Keep the volume low and comfortable for resting',
        'Avoid bright blue-light screens while winding down',
        'Do not wear tight headphones overnight if uncomfortable',
      ],
      iconIdentifier: 'Moon',
      colorToken: '#60A5FA',
      publishedAt: now,
      createdAt: now,
      updatedAt: now,
      provenance: 'system_seed',
      seedVersion: 1,
      createdBy: 'system_seed',
    },
    {
      id: 'article-4',
      title: 'Chakra Frequencies: Tuning Your Energy Body',
      content: `The chakra system originates in Indian spiritual and contemplative traditions, describing energy centres along the central axis of the body. Modern sound-healing systems associate specific musical pitch frequencies with each chakra — such as 194.18 Hz with the Root Chakra, 210.42 Hz with the Sacral, 126.22 Hz with the Solar Plexus, 341.3 Hz with the Heart, 384 Hz with the Throat, 426.7 Hz with the Third Eye, and 963 Hz with the Crown.\n\nIt is important to understand that frequency-to-chakra mappings vary across different sound-healing lineages and are not scientifically validated human anatomy or medical science.\n\nThese entries are presented as a contemporary meditation framework. Working through these frequencies sequentially provides a structured, mindful soundscape for self-reflection and energetic visualization.`,
      category: ArticleCategory.CHAKRAS,
      tags: ['chakra', 'energy', 'meditation', 'tradition', 'spiritual'],
      isPremium: false,
      status: ContentStatus.PUBLISHED,
      author: 'Frequency Lab',
      readTime: 9,
      difficulty: 'Beginner',
      keyPoints: [
        'Chakras are spiritual and contemplative concepts from Indian traditions',
        'Modern frequency mappings vary and are not scientifically validated anatomy',
        'Chakra soundscapes serve as a structured framework for meditation and visualization',
        'Sequential meditation offers a calming routine for mindfulness',
      ],
      practicalTips: [
        'Treat chakra soundscapes as a reflective meditation framework',
        'Spend 5–15 minutes per frequency during focused meditation',
        'Visualize calm color themes associated with each focus area',
        'Maintain a comfortable, relaxed posture',
      ],
      iconIdentifier: 'Zap',
      colorToken: '#FBBF24',
      publishedAt: now,
      createdAt: now,
      updatedAt: now,
      provenance: 'system_seed',
      seedVersion: 1,
      createdBy: 'system_seed',
    },
    {
      id: 'article-5',
      title: '528 Hz: The "Love Frequency" — What We Know and What We Don\'t',
      content: `The frequency 528 Hz holds a central place in modern Solfeggio sound therapy, frequently referred to as the "Love Frequency" or "Miracle Tone." Popular literature links 528 Hz to chlorophyll geometry, sacred ratios, and DNA.\n\nWhat does scientific research actually say? A small 2018 study by Akimoto et al. involving nine healthy participants observed reductions in cortisol and stress markers after participants listened to music tuned to 528 Hz compared to 440 Hz. However, the study evaluated music rather than an isolated pure tone, and the sample size was very small.\n\nClaims that 528 Hz repairs human DNA or cures biological disease are unsupported by clinical human evidence. 528 Hz remains a popular tone for heart-centered meditation and relaxation.`,
      category: ArticleCategory.SOLFEGGIO,
      tags: ['528hz', 'love frequency', 'wellness', 'research', 'meditation'],
      isPremium: false,
      status: ContentStatus.PUBLISHED,
      author: 'Frequency Lab',
      readTime: 8,
      difficulty: 'Intermediate',
      keyPoints: [
        '528 Hz is widely associated with love and transformation in modern sound therapy',
        'A small 2018 study (9 participants) noted cortisol changes after 528-Hz-tuned music',
        'The study tested music rather than an isolated pure tone',
        'Claims that 528 Hz repairs DNA or regenerates cells are not established by clinical science',
      ],
      practicalTips: [
        'Use 528 Hz as a tranquil backdrop for heart-focused meditation',
        'Listen for 5–20 minutes at a comfortable volume',
        'Combine with mindful breathing and positive self-reflection',
        'Do not rely on audio tones for medical conditions',
      ],
      scientificBasis: 'Akimoto et al. (2018) reported endocrine and autonomic changes in 9 healthy subjects listening to 528-Hz music. DNA repair claims remain unsupported in human clinical research.',
      iconIdentifier: 'Heart',
      colorToken: '#34D399',
      publishedAt: now,
      createdAt: now,
      updatedAt: now,
      provenance: 'system_seed',
      seedVersion: 1,
      createdBy: 'system_seed',
    },
    {
      id: 'article-6',
      title: "Schumann Resonance: Earth's Electromagnetic Phenomenon",
      content: `The Schumann Resonance is a well-documented geophysical atmospheric phenomenon. In 1952, physicist Winfried Otto Schumann predicted that the electromagnetic cavity between Earth's surface and the ionosphere would resonate at fundamental electromagnetic frequencies, starting near 7.83 Hz.\n\nBecause 7.83 Hz falls within the range of human Alpha and Theta brainwaves, many wellness practitioners draw parallels between planetary resonance and human consciousness.\n\nIt is important to distinguish physics from audio: phone speakers reproduce acoustic sound waves, not planetary electromagnetic fields. Schumann-inspired listening tracks offer an acoustic representation for grounding meditation, but do not reproduce Earth's electromagnetic field.`,
      category: ArticleCategory.HEALING,
      tags: ['Schumann', 'earth frequency', 'geophysics', 'grounding', '7.83hz'],
      isPremium: false,
      status: ContentStatus.PUBLISHED,
      author: 'Frequency Lab',
      readTime: 7,
      difficulty: 'Intermediate',
      keyPoints: [
        'Earth has fundamental atmospheric electromagnetic resonances near 7.83 Hz',
        '7.83 Hz falls mathematically within the alpha-theta brainwave boundary',
        'Phone audio generates acoustic sound waves, not planetary electromagnetic fields',
        'Schumann-inspired audio offers a soothing backdrop for grounding meditation',
      ],
      practicalTips: [
        'Use Schumann-inspired audio as a calm backdrop for outdoor or indoor meditation',
        'Combine with outdoor walks or quiet relaxation',
        'Listen at a comfortable, moderate volume',
        'Use for 5–20 minutes to settle a busy mind',
      ],
      iconIdentifier: 'Activity',
      colorToken: '#22D3EE',
      publishedAt: now,
      createdAt: now,
      updatedAt: now,
      provenance: 'system_seed',
      seedVersion: 1,
      createdBy: 'system_seed',
    },
    {
      id: 'article-7',
      title: 'Sound, Intention & Abundance: Using Music for Goal Reflection',
      content: `Using audio frequencies to support goal reflection and abundance draws on numerology, alternative musical tuning, and cognitive psychology.\n\nThe 888 Hz frequency carries numerological symbolism, where 8 represents flow and infinity. The 432 Hz tuning offers an alternative musical pitch that pilot studies suggest some listeners find calming. The 10 Hz Alpha frequency provides an environment for relaxed focus.\n\nPsychologically, listening to calming music while setting goals operates through cognitive priming — helping direct the Reticular Activating System (RAS) toward focused attention and goal setting.\n\nSound does not supernatural attract wealth; rather, intention, focus, journaling, and concrete personal action drive achievement.`,
      category: ArticleCategory.MANIFESTATION,
      tags: ['manifestation', 'abundance', '888hz', '432hz', 'psychology'],
      isPremium: true,
      status: ContentStatus.PUBLISHED,
      author: 'Frequency Lab',
      readTime: 8,
      difficulty: 'Intermediate',
      keyPoints: [
        '888 Hz carries traditional numerological symbolism for abundance reflection',
        '432 Hz is an alternative musical tuning used for calming focus',
        'Goal setting during audio sessions works through psychological focus and priming',
        'Sound does not magically attract wealth; concrete personal action creates success',
      ],
      practicalTips: [
        'Formulate clear personal goals before your listening session',
        'Journal concrete action steps immediately after listening',
        'Use 10 Hz Alpha or 432 Hz audio as a focus backdrop',
        'Practice daily goal reflection in a quiet space',
      ],
      iconIdentifier: 'Sparkles',
      colorToken: '#FBBF24',
      publishedAt: now,
      createdAt: now,
      updatedAt: now,
      provenance: 'system_seed',
      seedVersion: 1,
      createdBy: 'system_seed',
    },
    {
      id: 'article-8',
      title: '40 Hz Gamma Research: What Scientists Are Investigating',
      content: `Gamma brainwaves (30–100 Hz) represent fast neural oscillations associated with complex cognitive processing and perception. In recent years, 40 Hz sensory stimulation has become an active area of neuroscience research.\n\nLandmark research led by Dr. Li-Huei Tsai at MIT demonstrated that 40 Hz flickering light and auditory tones reduced amyloid and tau markers in mouse models of Alzheimer's disease. This led to ongoing human clinical trials evaluating neuroprotective mechanisms.\n\nWhile this research is legitimate and promising, clinical research protocols use controlled, specialized equipment. Playing a 40 Hz audio track through a commercial smartphone app is not a medical treatment for Alzheimer's disease or cognitive impairment.\n\n40 Hz audio provides an engaging backdrop for attentive study and focus.`,
      category: ArticleCategory.SCIENCE,
      tags: ['gamma', '40hz', 'neuroscience', 'cognitive', 'research', 'MIT'],
      isPremium: false,
      status: ContentStatus.PUBLISHED,
      author: 'Frequency Lab',
      readTime: 9,
      difficulty: 'Advanced',
      keyPoints: [
        '40 Hz falls in the gamma brainwave range associated with active cognition',
        'MIT studies investigate 40 Hz sensory stimulation in Alzheimer\'s models',
        'Human clinical trials are ongoing and preliminary',
        'A consumer audio track is not an Alzheimer\'s medical treatment',
      ],
      practicalTips: [
        'Use 40 Hz audio as a focus backdrop during study or work',
        'Keep sessions to 15–20 minutes as gamma frequencies are activating',
        'Listen at a comfortable volume during waking hours',
        'Combine with structured work or study goals',
      ],
      scientificBasis: 'Tsai et al. (MIT, 2016) demonstrated microglial and amyloid changes in mice using 40 Hz sensory stimulation. Human trials (Chan et al., 2022) remain exploratory.',
      iconIdentifier: 'Brain',
      colorToken: '#A78BFA',
      publishedAt: now,
      createdAt: now,
      updatedAt: now,
      provenance: 'system_seed',
      seedVersion: 1,
      createdBy: 'system_seed',
    },
  ];
}
